version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo-db
    environment:
      - NODE_ENV=development
    networks:
      - my-network

  mongo-db:
    hostname: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
